# name: k1-releaser

# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Generate Changelog
#         run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
#       - name: Release Foo
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           body_path: ${{ github.workspace }}-CHANGELOG.txt
#           token: ${{ secrets.GH_RELEASER_TOKEN }}
#         env:
#           GITHUB_REPOSITORY: AprendaCloud/foo

name: k1-releaser

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Foo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Release Kubefirst

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: AprendaCloud/foo

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

          # Optional. Tag name being created in the local repository and 
          # pushed to remote repository and defined branch.
          tagging_message: 'v1.0.0'
